### ISSUE TITLE
Simplify subscription to OSC by using *S (vs. *s)

### ISSUE THREAD

**Issue by pmaillot** [bitfocus/companion-module-behringer-wing#14]
(Note really an issue, but here goes...)

In the function below:

instance.prototype.pulse = function () {
	var self = this;
	self.sendOSC("/*s", []);
        .....

You could use *S instead of *s and receive a single OSC value rather than 3; This would certainly help in simplifying some of the functions, including fader level values that you would always receive (and send) in dB, avoiding the need for dB2float and float2dB.

Also glad to see the documentation I wrote has been useful :)

-Patrick-Gilles Maillot

**Comment by istnv** [comment]
@pmaillot Your docs have been extremely helpful! Thank you!
Internally, the module keeps track of fader position, not value. The float values from the console are the best source for this.
The module has an increment/decrement fader by a 'tick'. Not every float translates, though. Early versions of the module, you bump up 5, then bump down 5, and not end up back where you started. Specially when crossing between slope boundaries.
Internally the module generates an array equivalent of the float to db table from your docs. The bump up and down actions then walk this array. The only times the float conversions are actively used used is during a timed fade to keep the db variables updated.

**Comment by pmaillot** [comment]
John,

 

Thx,

That’s why I though using the *S would be helpful, especially for levels; Fader values are directly reported as dB, which are great for inc. or dec. 3dB (or 5) and keep track of fader position. No need to bother with a 1540 table of approximate float values, and even for cross fades, using a dB-based crossing function is more convenient from an auditive point of view.

 

-Patrick

**Comment by istnv** [comment]
It is also the same cross fade logic I use in the XAir module which only has float, so this saves me from 2 different routines.
The table is small, self generated and math is something the computer is good at. :)

**Comment by pmaillot** [comment]
OK then 😊

-Patrick
